vcpkg.json: New vcpkg requires builtin-baseline
Otherwise the vcpkg install CI step fails with the following message:

```
error: this vcpkg instance requires a manifest with a specified baseline
in order to interact with ports. Please add 'builtin-baseline' to the
manifest or add a 'vcpkg-configuration.json' that redefines the default
registry.
```